# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('sumA', models.FloatField(default=0.0)),
                ('sumB', models.FloatField(default=0.0)),
                ('averageA', models.FloatField(default=0.0)),
                ('averageB', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='all_data',
            field=models.ManyToManyField(to='siteApp.SiteDataEntry'),
        ),
    ]
