# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedataentry',
            old_name='data',
            new_name='description',
        ),
        migrations.AddField(
            model_name='sitedataentry',
            name='A_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sitedataentry',
            name='B_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sitedataentry',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
