# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0002_auto_20170318_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='averageA',
        ),
        migrations.RemoveField(
            model_name='site',
            name='averageB',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sumA',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sumB',
        ),
    ]
