# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_auto_20170319_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='all_data',
        ),
        migrations.AddField(
            model_name='sitedataentry',
            name='site_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='siteApp.Site'),
        ),
    ]
